library(RCurl)
library(plyr)
library(dplyr)
library(stringr)
getwd()

isit<-read.csv(file.path("Input","pdfs","extraction","named_entities.csv"))
isit$rowid<-1:nrow(isit)
my_db <- dplyr::src_sqlite("../sqlite-31.db", create = F)
isit$Verb<-str_extract(isit$Verb,"\\w+$")
isit1<-left_join(isit,distinct(tbl(my_db, sql("SELECT lemma,class from verbnetroles"))),by=c("Verb"="lemma"),copy=TRUE)
isit1$base_Class<-str_extract(isit1$class,"\\w+")
isit1$class_cat<-as.numeric(str_extract(isit1$class,"[0-9]+"))
base_guideline<-read.csv(textConnection(RCurl::getURL("https://docs.google.com/spreadsheets/d/1JBkTjHTW7YTRfHuJ-lZqjotK0XkvtdyI5tld-PUaQkw/pub?gid=0&single=true&output=csv")))
isit1<-left_join(isit1,base_guideline,by=c("class_cat"="Class"))
write.csv(isit1,file.path("Input","pdfs","extraction","verbs_categorized_multi_row.csv"))
isit2<-distinct(select(isit1,-Verb.Class))
write.csv(isit2,file.path("Input","pdfs","extraction","verbs_categorized_limited_row.csv"))