library(ggthemes)
library(ggthemes)
library(plyr)
library(dplyr)
attendance<-read.csv(file.path("Input","scraped_data","temp_cleaned_data.csv"))
talks<-read.csv(file.path("Input","pdfs","extraction","verbs_categorized_limited_row.csv"))
atm<-select(attendance,c(Name,Org,Meeting))
talks$Meeting<-gsub(".txt","",talks$Meeting)
talks<-left_join(talks,atm, by=c("Subject"="Name","Meeting"="Meeting"))
talks$VerbSmall<-as.character(talks$Verb.Type)
talks$VerbSmall[talks$VerbSmall%in%names(sort(table(talks$VerbSmall),decreasing=TRUE)[1:10])==FALSE]<-"OTHER VERB"
talks<-filter(talks,!duplicated(rowid))
talks$Orgbin<-as.character(talks$Org)
talks$Orgbin[talks$Org%in%names(sort(table(talks$Org),decreasing=T)[1:10])==FALSE]<-"Not Top 10"
talks$Date<-str_extract(talks$Meeting, "[0-9]+$|[0-9]+-[0-9]+-[0-9]+")
talks$Date<-ymd(talks$Date)
talks$y_m<-paste(year(talks$Date),month(talks$Date),sep="-")
talks$y_mround<-ymd(paste(talks$y_m,15,sep="-"))
talks$year<-year(talks$Date)
ggplotly(ggplot(talks)+geom_density(aes(x=year,fill=VerbSmall,),position="stack")+facet_wrap(~Orgbin,scale="free_y"))
bigtable<-reshape2::melt(xtabs(~VerbSmall+Orgbin+year,data=talks))
bigtable<-filter(bigtable, value>0)
ggplot(bigtable)+geom_smooth(aes(x=year,y=value,colour=Orgbin))+facet_wrap(~VerbSmall,scale="free_y")+scale_colour_tableau()+theme_minimal()
ggplot(filter(bigtable,Orgbin!="Not Top 10"))+geom_smooth(aes(x=year,y=value,colour=Orgbin))+facet_wrap(~VerbSmall,scale="free_y")+scale_colour_tableau()+theme_minimal()
ggplot(bigtable)+geom_smooth(aes(x=year,y=value,colour=VerbSmall))+facet_wrap(~Orgbin,scale="free_y")+scale_colour_tableau()+theme_minimal()
ggplot(filter(bigtable,VerbSmall!="OTHER VERB"))+geom_smooth(aes(x=year,y=value,colour=VerbSmall))+facet_wrap(~Orgbin,scale="free_y")+scale_colour_tableau()+theme_minimal()
ggplot(talks)+geom_density(aes(x=Date,..count..,fill=VerbSmall),position="stack")+scale_fill_tableau()+theme_minimal()
ggplot(talks)+geom_density(aes(x=Date,..count..,fill=VerbSmall),position="fill")+scale_fill_tableau()+theme_minimal()


